### ISSUE TITLE
Python 3.7 build error "too many arguments to function call, expected 3, have 4"

### ISSUE THREAD

**Issue by deeppunster** [OpenGov/cython_hunspell#10]
When attempting to install CyHunspell using Python 3.7 (under Mac OS 10.12.6) I get the above error.  Installing the same library under Python 3.6 on the same machine works fine.  Attached is the output from the failed build attempt.  The error is at line 133 in the text file (code location is hunspell/hunspell.cpp:8365).  Can you reproduce this error in your default environment?  if not, I will see if I can install Python 3.7 differently on my machine to get around the error.

[build_failure_info.txt](https://github.com/OpenGov/cython_hunspell/files/2168968/build_failure_info.txt)

**Comment by MSeal** [comment]
Hmm this is hard for me to reproduce as my linux machines don't have 3.7 available without building from scratch. It looks like a bump in the cython version used to compile the code will fix the issue, let me give that whirl today and try to get travis to test 3.7.

**Comment by MSeal** [comment]
Got the issue fixed -- just working through getting the mac os builds to pass again and I'll make a release tomorrow for it.

**Comment by deeppunster** [comment]
Verified.  Thanks for fixing this so quickly!
