### ISSUE TITLE
Python3 unicode error

### ISSUE THREAD

**Issue by chrisjbryant** [OpenGov/cython_hunspell#3]
Hiya,
I just started using CyHunspell 1.1.4 with Python3.
It works fine until I give it an accented word:
```
>>> h.spell("café")
UTF-8 encoding error. Missing continuation byte in 3. character position:
caf
False
```

**Comment by MSeal** [comment]
Hmm, what OS/exact python version are you running this on? Are you using any custom dictionaries or other configuration changes?

I get no error on 3.6.1 on windows, for example:
```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from hunspell import Hunspell
>>> h = Hunspell();
>>> h.spell("café")
False
```

**Comment by chrisjbryant** [comment]
So I think it's because I'm using a custom dictionary: en_GB-large. I don't get any error when I use the default dictionaries. 

I downloaded en_GB-large from [here](https://sourceforge.net/projects/wordlist/files/speller/2017.01.22/), unzipped and installed the .dic and .aff files in p3env/lib/python3.5/site-packages/dictionaries where the default dictionaries were installed. p3env is my own python3 [virtualenv](http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/) as I don't have admin rights on the server I'm using.
```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hunspell import Hunspell
>>> h = Hunspell("en_GB-large")
>>> h.spell("café")
UTF-8 encoding error. Missing continuation byte in 3. character position:
caf
False
```
Maybe I didn't install the new dictionary properly?

**Comment by MSeal** [comment]
Ok, thanks for the additional details. I was able to reproduce the issue with that dictionary file (you added the file to the correct default load path). The virtual environment, OS, and exact python version didn't matter. I imagine there's something in the dictionary to which it's trying to compare the last character and fails. Adding a space to the end of the input adds a work-around to the issue:

```
>>> h.spell("café")
UTF-8 encoding error. Missing continuation byte in 3. character position:
caf├
False
>>> h.spell("café ")
True
```

I'll work on a permanent fix in the near future once I narrow down where there's a mismatched (off-by-one?) error.

**Comment by chrisjbryant** [comment]
Ok, great, I'll keep a lookout for next version and use the work-around in the meantime. Thanks!

**Comment by MSeal** [comment]
Version 1.2.0 has a fix for the issue you found. It took me a while to address some automated build/library issues before I could get it released.
